import re
import glob
import os
import nltk
from trie import *
#from googletrans import Translator

#nltk.download('vader_lexicon')
unfound_words = []

#trie = Trie(language = "es", dict_size = 100000)

def limpiar_emojis_texto(texto):
    EMOJI_RE = re.compile("[\U00010000-\U0010FFFF]", flags=re.UNICODE)
    return EMOJI_RE.sub("", texto).strip()

def validar_emoji_en_texto(texto):
    EMOJI_RE = re.compile("[\U00010000-\U0010FFFF]", flags=re.UNICODE)
    resultado = bool(EMOJI_RE.search(texto))
    return resultado

def validar_alpha_en_texto(texto):
    ALPHA_RE = re.compile(r'[a-záéíóúüñA-ZÁÉÍÓÚÜÑ]')    
    resultado = bool(ALPHA_RE.search(texto))
    return resultado

def normalizacion_texto(texto):
    # Patrones fonéticos: trabajan dentro de palabras, sin \b
    texto = re.sub(r'phasta', 'hasta', texto)
    texto = re.sub(r'pha', 'pa', texto)
    texto = re.sub(r'phe', 'pe', texto)
    texto = re.sub(r'phi', 'pi', texto)
    texto = re.sub(r'pho', 'po', texto)
    texto = re.sub(r'phu', 'pu', texto)
    texto = re.sub(r'lha', 'la', texto)
    texto = re.sub(r'lhe', 'le', texto)
    texto = re.sub(r'lhi', 'li', texto)
    texto = re.sub(r'lho', 'lo', texto)
    texto = re.sub(r'lhu', 'lu', texto)
    texto = re.sub(r'kha', 'ka', texto)
    texto = re.sub(r'khe', 'ke', texto)
    texto = re.sub(r'khi', 'ki', texto)
    texto = re.sub(r'kho', 'ko', texto)
    texto = re.sub(r'khu', 'ku', texto)
    # Palabras completas con \b
    texto = re.sub(r'\bke\b', 'que', texto)
    texto = re.sub(r'\bpreokupes\b', 'preokupes', texto)
    texto = re.sub(r'\bcub\.', 'cubierta', texto)
    texto = re.sub(r'\bsr\b', 'señor', texto)
    texto = re.sub(r'\bokok\b', 'ok', texto)
    texto = re.sub(r'\bokrok\b', 'ok', texto)
    texto = re.sub(r'\bokis\b', 'ok', texto)
    texto = re.sub(r'\boky\b', 'ok', texto)
    texto = re.sub(r'\bokk\b', 'ok', texto)
    texto = re.sub(r'\bokd\b', 'ok', texto)
    texto = re.sub(r'\boki\b', 'ok', texto)
    texto = re.sub(r'\boks\b', 'ok', texto)
    texto = re.sub(r'\bokss\b', 'ok', texto)
    texto = re.sub(r'\bok+\b', 'ok', texto)
    texto = re.sub(r'\bokodoki\b', 'ok', texto)
    texto = re.sub(r'\bokoiki\b', 'ok', texto)
    texto = re.sub(r'\bokidoiki\b', 'ok', texto)
    texto = re.sub(r'\bgrs\b', 'gracias', texto)
    texto = re.sub(r'\bgraciasss\b', 'gracias', texto)
    texto = re.sub(r'gracia a', 'gracias a ti', texto)
    texto = re.sub(r'\bgracia\b', 'gracias', texto)
    texto = re.sub(r'\bgrax\b', 'gracias', texto)
    texto = re.sub(r'\bgraviss\b', 'gracias', texto)
    texto = re.sub(r'\bgracuas\b', 'gracias', texto)
    texto = re.sub(r'\bgraccias\b', 'gracias', texto)
    texto = re.sub(r'\bgracoas\b', 'gracias', texto)
    texto = re.sub(r'\bgravias\b', 'gracias', texto)
    texto = re.sub(r'\bpulgracias\b', 'gracias', texto)
    texto = re.sub(r'\bpagracias\b', 'gracias', texto)
    texto = re.sub(r'\bgarcias\b', 'gracias', texto)
    texto = re.sub(r'\bcorrecores\b', 'correctores', texto)
    texto = re.sub(r'\borale\b', 'órale', texto)
    texto = re.sub(r'\bntp\b', 'no te preocupes', texto)
    texto = re.sub(r'\bola\b', 'hola', texto)
    texto = re.sub(r'\bholis\b', 'hola', texto)
    texto = re.sub(r'\bpzas\b', 'piezas', texto)
    texto = re.sub(r'\bpzs\b', 'piezas', texto)
    texto = re.sub(r'\bpz\b', 'piezas', texto)
    texto = re.sub(r'\bpiezasa\b', 'piezas', texto)
    texto = re.sub(r'\bcomplmentos\b', 'complementos', texto)
    texto = re.sub(r'\bnuevamanete\b', 'nuevamente', texto)
    texto = re.sub(r'\bqui\b', 'que', texto)
    texto = re.sub(r'\bati\b', 'a ti', texto)
    texto = re.sub(r'\baty\b', 'a ti', texto)
    texto = re.sub(r'\bti,', 'a ti,', texto)
    texto = re.sub(r'\bondas\b', 'onda', texto)
    texto = re.sub(r'\blavoraste\b', 'laboraste', texto)
    texto = re.sub(r'\bbbuenas\b', 'buenas', texto)
    texto = re.sub(r'\buenas\b', 'buenas', texto)
    texto = re.sub(r'\bjesusi\b', 'jesus', texto)
    texto = re.sub(r'\bpork\b', 'porque', texto)
    texto = re.sub(r'\bxk\b', 'porque', texto)
    texto = re.sub(r'\basii\b', 'así', texto)
    texto = re.sub(r'\basi\b', 'así', texto)
    texto = re.sub(r'\bnop\b', 'no', texto)
    texto = re.sub(r'\bpasare\b', 'pasaré', texto)
    texto = re.sub(r'\beconomicas\b', 'económicas', texto)
    texto = re.sub(r'\bmas\b', 'más', texto)
    texto = re.sub(r'\basta\b', 'hasta', texto)
    texto = re.sub(r'\bud\b', 'usted', texto)
    texto = re.sub(r'\bpongame\b', 'póngame', texto)
    texto = re.sub(r'\baqui\b', 'aquí', texto)
    texto = re.sub(r'\bdiosas\b', 'dios', texto)
    texto = re.sub(r'\bdiosos\b', 'dios', texto)
    texto = re.sub(r'\bfui\b', 'fuí', texto)
    texto = re.sub(r'\boyes\b', 'oye', texto)
    texto = re.sub(r'\boie\b', 'oye', texto)
    texto = re.sub(r'\bsrita\b', 'señorita', texto)
    texto = re.sub(r'\bporfavorvor\b', 'porfavor', texto)
    texto = re.sub(r'\bcotizzacione\b', 'cotizaciones', texto)
    texto = re.sub(r'\bsirfavor\b', 'porfavor', texto)
    texto = re.sub(r'\bporfa\b', 'porfavor', texto)
    texto = re.sub(r'\bxfa\b', 'porfavor', texto)
    texto = re.sub(r'por fas', 'porfavor', texto)
    texto = re.sub(r'por favor', 'porfavor', texto)
    texto = re.sub(r'por fa', 'porfavor', texto)
    texto = re.sub(r'\btmb\b', 'también', texto)
    texto = re.sub(r'\blos ing\b', 'los ingenieros', texto)
    texto = re.sub(r'\bik\b', 'y que', texto)
    texto = re.sub(r'\boc\b', 'orden de compra', texto)
    texto = re.sub(r'\bnc\b', 'nota de credito', texto)
    texto = re.sub(r'\btc\b', 'tarjeta de credito', texto)
    texto = re.sub(r'\bfacturaturitas\b', 'facturas', texto)
    texto = re.sub(r'\bfacturaturar\b', 'facturar', texto)
    texto = re.sub(r'\bfacturature\b', 'factura', texto)
    texto = re.sub(r'\bfacturaturo\b', 'facturo', texto)
    texto = re.sub(r'\bfacturatura\b', 'factura', texto)
    texto = re.sub(r'\bfac\b', 'factura', texto)
    texto = re.sub(r'\bgad\b', 'gracias a dios', texto)
    texto = re.sub(r'\bbdias\b', 'buenos dias', texto)
    texto = re.sub(r'\bbdia\b', 'buen día', texto)
    texto = re.sub(r'buen dia', 'buen día', texto)
    texto = re.sub(r'\bandjunto\b', 'adjunto', texto)
    texto = re.sub(r'\baorita\b', 'ahorita', texto)
    texto = re.sub(r'\bahpraita\b', 'ahorita', texto)
    texto = re.sub(r'\borita\b', 'ahorita', texto)
    texto = re.sub(r'\bvd\b', 'verdad', texto)
    texto = re.sub(r'\babra\b', 'habra', texto)
    texto = re.sub(r'\bagregharemos\b', 'agregaremos', texto)
    texto = re.sub(r'\baleajandra\b', 'alejandra', texto)
    texto = re.sub(r'\bbieb\b', 'bien', texto)
    texto = re.sub(r'\bbienn\b', 'bien', texto)
    texto = re.sub(r'\bbnien\b', 'bien', texto)
    texto = re.sub(r'\bcres\b', 'crees', texto)
    texto = re.sub(r'\bcuanrto\b', 'cuanto', texto)
    texto = re.sub(r'\bdomucilio\b', 'domicilio', texto)
    texto = re.sub(r'\bnumero\b', 'número', texto)
    texto = re.sub(r'\beliminala\b', 'elimínala', texto)
    texto = re.sub(r'\bafrecido\b', 'ofrecido', texto)
    texto = re.sub(r'\bserca\b', 'cerca', texto)
    texto = re.sub(r'\bsipis\b', 'si', texto)
    texto = re.sub(r'\bsip\b', 'si', texto)
    texto = re.sub(r'\bsio\b', 'si', texto)
    texto = re.sub(r'\bsiii\b', 'si', texto)
    texto = re.sub(r'\bsii\b', 'si', texto)
    texto = re.sub(r'\bsimilhares\b', 'similares', texto)
    texto = re.sub(r'\bshabra\b', 'sabra', texto)
    texto = re.sub(r'\bsustitua\b', 'sustituya', texto)
    texto = re.sub(r'\bxfis\b', 'por favor', texto)
    texto = re.sub(r'\byaaaaa\b', 'ya', texto)
    texto = re.sub(r'\bvidaaaaa\b', 'vida', texto)
    texto = re.sub(r'\bplastoco\b', 'plastico', texto)
    texto = re.sub(r'\bviendop\b', 'viendo', texto)
    texto = re.sub(r'\bhh\b', 'h', texto)
    texto = re.sub(r'\bkh\b', 'k', texto)
    texto = re.sub(r'\bquew\b', 'que', texto)
    texto = re.sub(r'\bimg\b', 'imagen', texto)
    texto = re.sub(r'\baña\b', 'año', texto)
    texto = re.sub(r'\bpaq\b', 'paquete', texto)
    texto = re.sub(r'\brevisin\b', 'revision', texto)
    texto = re.sub(r'\bremisin\b', 'remision', texto)
    texto = re.sub(r'\bvisin\b', 'vision', texto)
    texto = re.sub(r'\bsomn\b', 'son', texto)
    texto = re.sub(r'\bsonj\b', 'son', texto)
    texto = re.sub(r'\bmañona\b', 'mañana', texto)
    texto = re.sub(r'\bacjas\b', 'cajas', texto)
    texto = re.sub(r'\bquie\b', 'que', texto)
    texto = re.sub(r'\bqueres\b', 'quieres', texto)
    texto = re.sub(r'\bqueren\b', 'quieren', texto)
    texto = re.sub(r'\bquere\b', 'quiere', texto)
    texto = re.sub(r'\bqueras\b', 'quieras', texto)
    texto = re.sub(r'\bquera\b', 'quiera', texto)
    texto = re.sub(r'\bquero\b', 'quiero', texto)
    texto = re.sub(r'\bestass\b', 'estas', texto)
    texto = re.sub(r'\besya\b', 'esta', texto)
    texto = re.sub(r'\belsta\b', 'esta', texto)
    texto = re.sub(r'\bps\b', 'pues', texto)
    texto = re.sub(r'\becho\b', 'hecho', texto)
    texto = re.sub(r'\bare\b', 'haré', texto)
    texto = re.sub(r'\bproximo\b', 'próximo', texto)
    texto = re.sub(r'\bcu\b', 'cada una', texto)
    texto = re.sub(r'\bunaanto\b', 'cuanto', texto)
    texto = re.sub(r'\bytu\b', 'y tu', texto)
    texto = re.sub(r'\baun\b', 'aún', texto)
    texto = re.sub(r'\bpodia\b', 'podía', texto)
    texto = re.sub(r'\bpodra\b', 'podrá', texto)
    texto = re.sub(r'\bpodrias\b', 'podrías', texto)
    texto = re.sub(r'\bllegarian\b', 'llegarían', texto)
    texto = re.sub(r'\bllegaria\b', 'llegaría', texto)
    texto = re.sub(r'\benvies\b', 'envíes', texto)
    texto = re.sub(r'\benvias\b', 'envías', texto)
    texto = re.sub(r'\benvio\b', 'envío', texto)
    texto = re.sub(r'\berann\b', 'eran', texto)
    texto = re.sub(r'\bseran\b', 'serán', texto)
    texto = re.sub(r'\bpence\b', 'pensé', texto)
    texto = re.sub(r'\bmandamelo\b', 'mándamelo', texto)
    texto = re.sub(r'\bmandame\b', 'mándame', texto)
    texto = re.sub(r'\bnetro\b', 'neto', texto)
    texto = re.sub(r'\bsalocitar\b', 'solicitar', texto)
    texto = re.sub(r'\bagreagar\b', 'agregar', texto)
    texto = re.sub(r'\bagregharemos\b', 'agregaremos', texto)
    texto = re.sub(r'\bunaal\b', 'una', texto)
    texto = re.sub(r'\bapieza\b', 'una pieza', texto)
    texto = re.sub(r'what app', 'whatsapp', texto)
    texto = re.sub(r'\bimprimi\b', 'imprimí', texto)
    texto = re.sub(r'\bsubi\b', 'subí', texto)
    texto = re.sub(r'\bbiolencia\b', 'violencia', texto)
    texto = re.sub(r'\bremision\b', 'remisión', texto)
    texto = re.sub(r'\bguia\b', 'guía', texto)
    texto = re.sub(r'\bquen\b', 'quien', texto)
    texto = re.sub(r'\bquien\b', 'quién', texto)
    texto = re.sub(r'\bpal\b', 'para', texto)
    texto = re.sub(r'\besquela\b', 'escuela', texto)
    texto = re.sub(r'\besperhar[eé]\b', 'esperaré', texto)
    texto = re.sub(r'\besperhar\b', 'esperar', texto)
    texto = re.sub(r'\bcotice\b', 'coticé', texto)
    texto = re.sub(r'\bcuanto\b', 'cuánto', texto)
    texto = re.sub(r'\bcuantas\b', 'cuántas', texto)
    texto = re.sub(r'\bcuantos\b', 'cuántos', texto)
    texto = re.sub(r'\bacrilico\b', 'acrílico', texto)
    texto = re.sub(r'\brazon\b', 'razón', texto)
    texto = re.sub(r'\bmerida\b', 'mérida', texto)
    texto = re.sub(r'\bperdon\b', 'perdón', texto)
    texto = re.sub(r'\bdioso\b', 'dios', texto, flags=re.IGNORECASE)
    texto = re.sub(r'\bpagaria\b', 'pagaría', texto)
    texto = re.sub(r'con ña', 'con la', texto)
    texto = re.sub(r'\beh\b', 'he', texto)
    texto = re.sub(r'\bplimas\b', 'plumas', texto)
    texto = re.sub(r'\bhunmedas\b', 'húmedas', texto)
    texto = re.sub(r'\balguos\b', 'algunos', texto)
    texto = re.sub(r'\balgun\b', 'algún', texto)
    texto = re.sub(r'\bperame\b', 'espérame', texto)
    texto = re.sub(r'\bcotizacion\b', 'cotización', texto)
    texto = re.sub(r'\bpregunte\b', 'pregunté', texto)
    texto = re.sub(r'\blapiz\b', 'lápiz', texto)
    texto = re.sub(r'carpetade de', 'carpeta de', texto)
    texto = re.sub(r'\bjjaja\b', 'jaja', texto)
    texto = re.sub(r'\bgenerico\b', 'genérico', texto)
    texto = re.sub(r'\bsabado\b', 'sábado', texto)
    texto = re.sub(r'\brebice\b', 'revisé', texto)
    texto = re.sub(r'\brevise\b', 'revisé', texto)
    texto = re.sub(r'\bjrje\b', 'jeje', texto)
    texto = re.sub(r'\bbtardes\b', 'buenas tardes', texto)
    texto = re.sub(r'\bsholamente\b', 'solamente', texto)
    texto = re.sub(r'<se editó este mensaje\.>', '', texto)
    texto = re.sub(r'\baya\b', 'allá', texto)
    texto = re.sub(r'\bnomnre\b', 'nombre', texto)
    texto = re.sub(r'\bnuevp\b', 'nuevo', texto)
    texto = re.sub(r'\bbartatos\b', 'baratos', texto)
    texto = re.sub(r'\beip\b', 'sip', texto)
    texto = re.sub(r'\btuk\b', 'tu', texto)
    texto = re.sub(r'\bsi+\b', 'si', texto)
    texto = re.sub(r'\bsubio\b', 'subió', texto)
    texto = re.sub(r'\bnose\b', 'no sé', texto)
    texto = re.sub(r'\besta\b', 'está', texto)
    texto = re.sub(r'(\d)([a-záéíóúüñ])', r'\1 \2', texto)
    texto = re.sub(r'([a-záéíóúüñ])(\d)', r'\1 \2', texto)
    texto = re.sub(r'\bacualizo\b', 'actualizó', texto)
    texto = re.sub(r'\bdanela\b', 'daniela', texto)
    texto = re.sub(r'\baki\b', 'aquí', texto)
    texto = re.sub(r'\bbueos\b', 'buenos', texto)
    texto = re.sub(r'\bmdia\b', 'día', texto)
    texto = re.sub(r'\bfacturad\b', 'facturas', texto)
    texto = re.sub(r'\bacordion\b', 'acordión', texto)
    texto = re.sub(r'\bgenerl\b', 'general', texto)
    texto = re.sub(r'\bemos\b', 'hemos', texto)
    texto = re.sub(r'\bqueriendome\b', 'queriéndome', texto)
    texto = re.sub(r'\btodavia\b', 'todavía', texto)
    texto = re.sub(r'\bnombré\b', 'nombre', texto)
    texto = re.sub(r'\brios\b', 'ríos', texto)
    texto = re.sub(r'\bhara\b', 'hará', texto)
    texto = re.sub(r'\bmande\b', 'mandé', texto)
    texto = re.sub(r'\bpagaran\b', 'pagarán', texto)
    texto = re.sub(r'\bfacturp\b', 'facturó', texto)
    texto = re.sub(r'\bagoto\b', 'agotó', texto)
    texto = re.sub(r'\bmanod\b', 'mandó', texto)
    texto = re.sub(r'\bpedidp\b', 'pedido', texto)
    texto = re.sub(r'\btambien\b', 'también', texto)
    texto = re.sub(r'\bperdoname\b', 'perdóname', texto)
    texto = re.sub(r'\bseria\b', 'sería', texto)
    texto = re.sub(r'\bojal\b', 'ojalá', texto)
    texto = re.sub(r'\bojala\b', 'ojalá', texto)
    texto = re.sub(r'\btermicas\b', 'térmicas', texto)
    texto = re.sub(r'\bvz\b', 'vez', texto)
    texto = re.sub(r'\bponcho\b', 'ponchó', texto)
    texto = re.sub(r'\bnummero\b', 'número', texto)
    texto = re.sub(r'\bnumero\b', 'número', texto)
    texto = re.sub(r'\bdr\b', 'doctor', texto)
    texto = re.sub(r'\btardaria\b', 'tardaría', texto)
    texto = re.sub(r'\bekivoke\b', 'equivoqué', texto)
    texto = re.sub(r'\boiga\b', 'oye', texto)
    texto = re.sub(r'\bhabria\b', 'habría', texto)
    texto = re.sub(r'\bfacturrame\b', 'factúrame', texto)
    texto = re.sub(r'\bpapeleria\b', 'papelería', texto)
    texto = re.sub(r'\bocupas\b', 'necesitas', texto)
    texto = re.sub(r'\bpsas\b', 'pasas', texto)
    texto = re.sub(r'\bcargolla\b', 'argolla', texto)
    texto = re.sub(r'\bcotizaconi\b', 'cotización', texto)
    texto = re.sub(r'\bcotizacion\b', 'cotización', texto)
    texto = re.sub(r'\bformaton\b', 'formato', texto)
    texto = re.sub(r'\bporfavorvoe\b', 'porfavor', texto)
    texto = re.sub(r'\badquisicion\b', 'adquisición', texto)
    texto = re.sub(r'\bpagare\b', 'pagaré', texto)
    texto = re.sub(r'\bcotizare\b', 'cotizaré', texto)
    texto = re.sub(r'\btraeran\b', 'traerán', texto)
    texto = re.sub(r'\bplumon\b', 'plumón', texto)
    texto = re.sub(r'\bpermiteme\b', 'permítame', texto)
    texto = re.sub(r'\bprob\b', 'problema', texto)
    texto = re.sub(r'\bavisasi\b', 'avisas', texto)
    texto = re.sub(r'\bdire\b', 'diré', texto)
    texto = re.sub(r'\bcirto\b', 'cierto', texto)
    texto = re.sub(r'\barticulo\b', 'artículo', texto)
    texto = re.sub(r'\bavsio\b', 'aviso', texto)
    texto = re.sub(r'\bocmo\b', 'cómo', texto)
    texto = re.sub(r'\bya ingrese\b', 'ya ingresé', texto)
    texto = re.sub(r'\bcolres\b', 'colores', texto)
    texto = re.sub(r'\bkilomtricas\b', 'kilométricas', texto)
    texto = re.sub(r'\bbolando\b', 'volando', texto)
    texto = re.sub(r'\barea\b', 'área', texto)
    texto = re.sub(r'\btines\b', 'tienes', texto)
    texto = re.sub(r'\bijole\b', 'híjole', texto)
    texto = re.sub(r'\bsegun\b', 'según', texto)
    texto = re.sub(r'\bentendi\b', 'entendí', texto)
    texto = re.sub(r'\btoco\b', 'tocó', texto)
    texto = re.sub(r'\bsientiendo\b', 'sintiendo', texto)
    texto = re.sub(r'\bsucursalursal\b', 'sucursal', texto)
    texto = re.sub(r'\bsucursaleder\b', 'suceder', texto)
    texto = re.sub(r'\bpapapeleria\b', 'papelería', texto)
    texto = re.sub(r'\bcontestabass\b', 'contestabas', texto)
    texto = re.sub(r'\bmoficiando\b', 'modificando', texto)
    texto = re.sub(r'\bregistratme\b', 'registrarme', texto)
    texto = re.sub(r'\bporqyue\b', 'porque', texto)
    texto = re.sub(r'\bfacrura\b', 'factura', texto)
    texto = re.sub(r'\benttegan\b', 'entregan', texto)
    texto = re.sub(r'\bgenerara\b', 'generará', texto)
    texto = re.sub(r'\bgenerara\b', 'generará', texto)
    texto = re.sub(r'\bgenerera\b', 'genera', texto)
    texto = re.sub(r'\bmucgas\b', 'muchas', texto)
    texto = re.sub(r'\bdiculpa\b', 'disculpa', texto)
    texto = re.sub(r'\bholka\b', 'hola', texto)
    texto = re.sub(r'\bbuenida\b', 'buen día', texto)
    texto = re.sub(r'\bporfavorzote\b', 'porfavor', texto)
    texto = re.sub(r'\bporfavorvaor\b', 'porfavor', texto)
    texto = re.sub(r'\bprofavorvir\b', 'porfavor', texto)
    texto = re.sub(r'\bokiroki\b', 'ok', texto)
    texto = re.sub(r'\bselecras\b', 'selectas', texto)
    texto = re.sub(r'\bcarns\b', 'carnes', texto)
    texto = re.sub(r'\badquicision\b', 'adquisición', texto)
    texto = re.sub(r'\bcotifce\b', 'coticé', texto)
    texto = re.sub(r'\bpercate\b', 'percaté', texto)
    texto = re.sub(r'\bgde\b', 'grande', texto)
    texto = re.sub(r'\bgcs\b', 'gracias', texto)
    texto = re.sub(r'\bgdes\b', 'grandes', texto)
    texto = re.sub(r'\bgraacias\b', 'gracias', texto)
    texto = re.sub(r'\bgrac\b', 'gracias', texto)
    texto = re.sub(r'\bgraciaas\b', 'gracias', texto)
    texto = re.sub(r'\bgracis\b', 'gracias', texto)
    texto = re.sub(r'\bgr\b', 'gracias', texto)
    texto = re.sub(r'\bgrs\b', 'gracias', texto)
    texto = re.sub(r'\bgustoo\b', 'gracias', texto)
    texto = re.sub(r'\bhaa\b', 'ha', texto)
    texto = re.sub(r'\bvaca\b', 'vacaciones', texto)
    texto = re.sub(r'\bubicacion\b', 'ubicación', texto)
    texto = re.sub(r'\btwngas\b', 'tengas', texto)
    texto = re.sub(r'\baagregas\b', 'agregas', texto)
    texto = re.sub(r'\bago\b', 'agosto', texto)
    texto = re.sub(r'\bdirefencia\b', 'diferencia', texto)

    # correcciones inferidas de domain_dict_by_topic
    texto = re.sub(r'\baciete\b', 'aceite', texto)
    texto = re.sub(r'\badesiva\b', 'adhesiva', texto)
    texto = re.sub(r'\badesivas\b', 'adhesivas', texto)
    texto = re.sub(r'\baguno\b', 'alguno', texto)
    texto = re.sub(r'\bamarila\b', 'amarilla', texto)
    texto = re.sub(r'\bampaque\b', 'empaque', texto)
    texto = re.sub(r'\baparecuo\b', 'apareció', texto)
    texto = re.sub(r'\baser\b', 'hacer', texto)
    texto = re.sub(r'\bautmaticos\b', 'automáticos', texto)
    texto = re.sub(r'\baveces\b', 'a veces', texto)
    texto = re.sub(r'\baveses\b', 'a veces', texto)
    texto = re.sub(r'\baydar\b', 'ayudar', texto)
    texto = re.sub(r'\bazcar\b', 'azúcar', texto)
    texto = re.sub(r'\bbiem\b', 'bien', texto)
    texto = re.sub(r'\bbiene\b', 'bien', texto)
    texto = re.sub(r'\bbine\b', 'bien', texto)
    texto = re.sub(r'\bbolsasa\b', 'bolsas', texto)
    texto = re.sub(r'\bboniita\b', 'bonita', texto)
    texto = re.sub(r'\bbuanas\b', 'buenas', texto)
    texto = re.sub(r'\bbuenaas\b', 'buenas', texto)
    texto = re.sub(r'\bcalro\b', 'claro', texto)
    texto = re.sub(r'\bcancelaccion\b', 'cancelación', texto)
    texto = re.sub(r'\bcancelaraa\b', 'cancelará', texto)
    texto = re.sub(r'\bcarapetas\b', 'carpetas', texto)
    texto = re.sub(r'\bcarptas\b', 'carpetas', texto)
    texto = re.sub(r'\bccordon\b', 'cordón', texto)
    texto = re.sub(r'\bcilicon\b', 'silicón', texto)
    texto = re.sub(r'\bclaaro\b', 'claro', texto)
    texto = re.sub(r'\bcoasa\b', 'cosa', texto)
    texto = re.sub(r'\bcoicidir\b', 'coincidir', texto)
    texto = re.sub(r'\bcomenaron\b', 'comenzaron', texto)
    texto = re.sub(r'\bconstacia\b', 'constancia', texto)
    texto = re.sub(r'\bcontancia\b', 'constancia', texto)
    texto = re.sub(r'\bcptozas\b', 'cotizas', texto)
    texto = re.sub(r'\bctizas\b', 'cotizas', texto)
    texto = re.sub(r'\bcuaanto\b', 'cuánto', texto)
    texto = re.sub(r'\bcualcuer\b', 'cualquier', texto)
    texto = re.sub(r'\bcualqueir\b', 'cualquier', texto)
    texto = re.sub(r'\bcuanl\b', 'cuál', texto)
    texto = re.sub(r'\bcuatos\b', 'cuántos', texto)
    texto = re.sub(r'\bdaniela+\b', 'daniela', texto)
    texto = re.sub(r'\bdeacuerdo\b', 'de acuerdo', texto)
    texto = re.sub(r'\bdeve\b', 'debe', texto)
    texto = re.sub(r'\bdifencia\b', 'diferencia', texto)
    texto = re.sub(r'\bdireferencia\b', 'diferencia', texto)
    texto = re.sub(r'\bdirerencia\b', 'diferencia', texto)
    texto = re.sub(r'\bdomiclio\b', 'domicilio', texto)
    texto = re.sub(r'\benccuentras\b', 'encuentras', texto)
    texto = re.sub(r'\bencuentrres\b', 'encuentres', texto)
    texto = re.sub(r'\benecaergo\b', 'encargo', texto)
    texto = re.sub(r'\bengradora\b', 'engrapadora', texto)
    texto = re.sub(r'\bentraga\b', 'entrega', texto)
    texto = re.sub(r'\bentregae\b', 'entrega', texto)
    texto = re.sub(r'\bentrregue\b', 'entregue', texto)
    texto = re.sub(r'\benttregan\b', 'entregan', texto)
    texto = re.sub(r'\bepuede\b', 'puede', texto)
    texto = re.sub(r'\besasa\b', 'esas', texto)
    texto = re.sub(r'\bescelente\b', 'excelente', texto)
    texto = re.sub(r'\bescolres\b', 'escolares', texto)
    texto = re.sub(r'\bespara\b', 'espera', texto)
    texto = re.sub(r'\bexclente\b', 'excelente', texto)
    texto = re.sub(r'\bfacruras\b', 'facturas', texto)
    texto = re.sub(r'\bfactgure\b', 'facture', texto)
    texto = re.sub(r'\bfacutura\b', 'factura', texto)
    texto = re.sub(r'\bfacuta\b', 'factura', texto)
    texto = re.sub(r'\bfacuto\b', 'facturó', texto)
    texto = re.sub(r'\bfcaturar\b', 'facturar', texto)
    texto = re.sub(r'\bfloorecentes\b', 'fluorescentes', texto)
    texto = re.sub(r'\bfoavor\b', 'favor', texto)
    texto = re.sub(r'\bfoldwr\b', 'folder', texto)
    texto = re.sub(r'\bfsvor\b', 'favor', texto)
    texto = re.sub(r'\bfuncioa\b', 'funciona', texto)
    texto = re.sub(r'\bgafette\b', 'gafete', texto)
    texto = re.sub(r'\bgrcaias\b', 'gracias', texto)
    texto = re.sub(r'\bhcaer\b', 'hacer', texto)
    texto = re.sub(r'\bhisiste\b', 'hiciste', texto)
    texto = re.sub(r'\bhoal\b', 'hola', texto)
    texto = re.sub(r'\bhojala\b', 'ojalá', texto)
    texto = re.sub(r'\bigaul\b', 'igual', texto)
    texto = re.sub(r'\bigaula\b', 'igual', texto)
    texto = re.sub(r'\bitalina\b', 'italiana', texto)
    texto = re.sub(r'\bkerias\b', 'querías', texto)
    texto = re.sub(r'\bkieres\b', 'quieres', texto)
    texto = re.sub(r'\bkomo\b', 'como', texto)
    texto = re.sub(r'\bmarcaodres\b', 'marcadores', texto)
    texto = re.sub(r'\bmarcatexots\b', 'marca textos', texto)
    texto = re.sub(r'\bmarcatxto\b', 'marcatexto', texto)
    texto = re.sub(r'\bmiercoles\b', 'miércoles', texto)
    texto = re.sub(r'\bmoemnto\b', 'momento', texto)
    texto = re.sub(r'\bmomneto\b', 'momento', texto)
    texto = re.sub(r'\bmorocidad\b', 'morosidad', texto)
    texto = re.sub(r'\bnarajna\b', 'naranja', texto)
    texto = re.sub(r'\bncesito\b', 'necesito', texto)
    texto = re.sub(r'\bneceitan\b', 'necesitan', texto)
    texto = texto.replace('necesinecesito', 'necesito')
    texto = texto.replace('necestar', 'necesitar')
    texto = re.sub(r'\bnformes\b', 'informes', texto)
    texto = re.sub(r'\bnuemro\b', 'número', texto)
    texto = re.sub(r'\boficcina\b', 'oficina', texto)
    texto = re.sub(r'\bofice\b', 'oficina', texto)
    texto = re.sub(r'\boficicio\b', 'oficio', texto)
    texto = re.sub(r'\bofico\b', 'oficio', texto)
    texto = re.sub(r'\bofina\b', 'oficina', texto)
    texto = re.sub(r'\bopalalina\b', 'opalina', texto)
    texto = re.sub(r'\borgnizador\b', 'organizador', texto)
    texto = re.sub(r'\bpapeleleria\b', 'papelería', texto)
    texto = re.sub(r'\bpapleria\b', 'papelería', texto)
    texto = re.sub(r'\bpaqete\b', 'paquete', texto)
    texto = re.sub(r'\bpaqueets\b', 'paquetes', texto)
    texto = re.sub(r'\bparese\b', 'parece', texto)
    texto = re.sub(r'\bpediticiones\b', 'peticiones', texto)
    texto = re.sub(r'\bpednien\b', 'piden', texto)
    texto = re.sub(r'\bpeude\b', 'puede', texto)
    texto = re.sub(r'\bpeudes\b', 'puedes', texto)
    texto = re.sub(r'\bpiesas\b', 'piezas', texto)
    texto = re.sub(r'\bplaticos\b', 'plásticos', texto)
    texto = re.sub(r'\bproblama\b', 'problema', texto)
    texto = re.sub(r'\bprofesianl\b', 'profesional', texto)
    texto = re.sub(r'\bprovado\b', 'probado', texto)
    texto = re.sub(r'\bprovedor\b', 'proveedor', texto)
    texto = re.sub(r'\bprovedores\b', 'proveedores', texto)
    texto = re.sub(r'\bproveedore\b', 'proveedor', texto)
    texto = re.sub(r'\bqe\b', 'que', texto)
    texto = re.sub(r'\bqie\b', 'que', texto)
    texto = re.sub(r'\bquciera\b', 'quisiera', texto)
    texto = re.sub(r'\bqueeren\b', 'quieren', texto)
    texto = re.sub(r'\bquires\b', 'quieres', texto)
    texto = re.sub(r'\bremplasan\b', 'reemplazan', texto)
    texto = re.sub(r'\bresiviendo\b', 'recibiendo', texto)
    texto = re.sub(r'\brespuestos\b', 'repuestos', texto)
    texto = re.sub(r'\bretular\b', 'rotular', texto)
    texto = re.sub(r'\brotafoleo\b', 'rotafolio', texto)
    texto = re.sub(r'\brotuladp\b', 'rotulado', texto)
    texto = re.sub(r'\bsabados\b', 'sábados', texto)
    texto = re.sub(r'\bscaner\b', 'escáner', texto)
    texto = re.sub(r'\bsemos\b', 'somos', texto)
    texto = re.sub(r'\bsiguente\b', 'siguiente', texto)
    texto = re.sub(r'\bsiuguiente\b', 'siguiente', texto)
    texto = re.sub(r'\bsimpre\b', 'siempre', texto)
    texto = re.sub(r'\bsolcitar\b', 'solicitar', texto)
    texto = re.sub(r'\bsolictar\b', 'solicitar', texto)
    texto = re.sub(r'\bstok\b', 'stock', texto)
    texto = re.sub(r'\bsujetacumentos\b', 'sujetadocumentos', texto)
    texto = re.sub(r'\bsujetadocumetos\b', 'sujetadocumentos', texto)
    texto = re.sub(r'\bsuperisora\b', 'supervisora', texto)
    texto = re.sub(r'\btambein\b', 'también', texto)
    texto = re.sub(r'\btambiel\b', 'también', texto)
    texto = re.sub(r'\btandarian\b', 'tardarían', texto)
    texto = re.sub(r'\btarddes\b', 'tardes', texto)
    texto = re.sub(r'\btedra\b', 'tendrá', texto)
    texto = re.sub(r'\btemando\b', 'tomando', texto)
    texto = re.sub(r'\bterjetas\b', 'tarjetas', texto)
    texto = re.sub(r'\btexxto\b', 'texto', texto)
    texto = re.sub(r'\bthemos\b', 'tenemos', texto)
    texto = re.sub(r'\btibimos\b', 'tuvimos', texto)
    texto = re.sub(r'\btibiste\b', 'tuviste', texto)
    texto = re.sub(r'\btiemes\b', 'tienes', texto)
    texto = re.sub(r'\btienpo\b', 'tiempo', texto)
    texto = re.sub(r'\btirno\b', 'turno', texto)
    texto = re.sub(r'\btiviste\b', 'tuviste', texto)
    texto = re.sub(r'\btmbn\b', 'también', texto)
    texto = re.sub(r'\btraegan\b', 'traigan', texto)
    texto = re.sub(r'\btrane\b', 'traen', texto)
    texto = re.sub(r'\btranparentes\b', 'transparentes', texto)
    texto = re.sub(r'\btransferncia\b', 'transferencia', texto)
    texto = re.sub(r'\btransperente\b', 'transparente', texto)
    texto = re.sub(r'\btrasparente\b', 'transparente', texto)
    texto = re.sub(r'\btrasparentes\b', 'transparentes', texto)
    texto = re.sub(r'\btrensado\b', 'trenzado', texto)
    texto = re.sub(r'\bttanscurso\b', 'transcurso', texto)
    texto = re.sub(r'\btuallitas\b', 'toallitas', texto)
    texto = re.sub(r'\bunsted\b', 'usted', texto)
    texto = re.sub(r'\bustede\b', 'usted', texto)
    texto = re.sub(r'\busteedes\b', 'ustedes', texto)
    texto = re.sub(r'\bustes\b', 'ustedes', texto)
    texto = re.sub(r'\bvama\b', 'vamos', texto)
    texto = re.sub(r'\bvanmos\b', 'vamos', texto)
    texto = re.sub(r'\bverdees\b', 'verdes', texto)
    texto = re.sub(r'\bverds\b', 'verdes', texto)
    texto = re.sub(r'\bxfavor\b', 'porfavor', texto)
    texto = re.sub(r'\babrian\b', 'abrían', texto)
    texto = re.sub(r'\baca\b', 'acá', texto)
    texto = re.sub(r'\baceptacion\b', 'aceptación', texto)
    texto = re.sub(r'\baceptaran\b', 'aceptarán', texto)
    texto = re.sub(r'\baceptaron\b', 'aceptaron', texto)
    texto = re.sub(r'\bacordeon\b', 'acordeón', texto)
    texto = re.sub(r'\bacordión\b', 'acordeón', texto)
    texto = re.sub(r'\bacrilicos\b', 'acrílicos', texto)
    texto = re.sub(r'\bactualizacion\b', 'actualización', texto)
    texto = re.sub(r'\bactualizo\b', 'actualizó', texto)
    texto = re.sub(r'\bacuerdate\b', 'acuérdate', texto)
    texto = re.sub(r'\bademas\b', 'además', texto)
    texto = re.sub(r'\badquisción\b', 'adquisición', texto)
    texto = re.sub(r'\bagradeceria\b', 'agradecería', texto)
    texto = re.sub(r'\bagotame\b', 'aguántame', texto)
    texto = re.sub(r'\bagoto\b', 'agotó', texto)
    texto = re.sub(r'\bagrege\b', 'agregué', texto)
    texto = re.sub(r'\baguanta\b', 'aguanta', texto)
    texto = re.sub(r'\baguantame\b', 'aguántame', texto)
    texto = re.sub(r'\bagusto\b', 'a gusto', texto)
    texto = re.sub(r'\bahacer\b', 'a hacer', texto)
    texto = re.sub(r'\bahi\b', 'ahí', texto)
    texto = re.sub(r'\balambrico\b', 'alámbrico', texto)
    texto = re.sub(r'\balcansan\b', 'alcanzan', texto)
    texto = re.sub(r'\balla\b', 'allá', texto)
    texto = re.sub(r'\balmacen\b', 'almacén', texto)
    texto = re.sub(r'\bami\b', 'a mí', texto)
    texto = re.sub(r'\bamndo\b', 'mandando', texto)
    texto = re.sub(r'\banotartelos\b', 'anotártelos', texto)
    texto = re.sub(r'\bapasar\b', 'a pasar', texto)
    texto = re.sub(r'\bapedir\b', 'a pedir', texto)
    texto = re.sub(r'\bapquete\b', 'paquete', texto)
    texto = re.sub(r'\baprimera\b', 'a primera', texto)
    texto = re.sub(r'\bapromera\b', 'a primera', texto)
    texto = re.sub(r'\bapsando\b', 'pasando', texto)
    texto = re.sub(r'\barecoger\b', 'a recoger', texto)
    texto = re.sub(r'\barevision\b', 'a revisión', texto)
    texto = re.sub(r'\barhivero\b', 'archivero', texto)
    texto = re.sub(r'\barticulos\b', 'artículos', texto)
    texto = re.sub(r'\basolicitar\b', 'a solicitar', texto)
    texto = re.sub(r'\batencion\b', 'atención', texto)
    texto = re.sub(r'\batras\b', 'atrás', texto)
    texto = re.sub(r'\bautorizacion\b', 'autorización', texto)
    texto = re.sub(r'\baver\b', 'a ver', texto)
    texto = re.sub(r'\bayudame\b', 'ayúdame', texto)
    texto = re.sub(r'\bazucar\b', 'azúcar', texto)
    texto = re.sub(r'\bbajio\b', 'bajío', texto)
    texto = re.sub(r'\bbanbajio\b', 'Banbajío', texto)
    texto = re.sub(r'\bbasica\b', 'básica', texto)
    texto = re.sub(r'\bbaterias\b', 'baterías', texto)
    texto = re.sub(r'\bbaño\b', 'baño', texto)
    texto = re.sub(r'\bbitacora\b', 'bitácora', texto)
    texto = re.sub(r'\bboligrafo\b', 'bolígrafo', texto)
    texto = re.sub(r'\bbuenastardes\b', 'buenas tardes', texto)
    texto = re.sub(r'\bbuendia\b', 'buen día', texto)
    texto = re.sub(r'\bcafe\b', 'café', texto)
    texto = re.sub(r'\bcafeteria\b', 'cafetería', texto)
    texto = re.sub(r'\bcancelacion\b', 'cancelación', texto)
    texto = re.sub(r'\bcaracteristicas\b', 'características', texto)
    texto = re.sub(r'\bcarbon\b', 'carbón', texto)
    texto = re.sub(r'\bcatalogo\b', 'catálogo', texto)
    texto = re.sub(r'\bchecalo\b', 'chécalo', texto)
    texto = re.sub(r'\bcomun\b', 'común', texto)
    texto = re.sub(r'\bcomunicacion\b', 'comunicación', texto)
    texto = re.sub(r'\bconfirmacion\b', 'confirmación', texto)
    texto = re.sub(r'\bcoti\b', 'cotización', texto)
    texto = re.sub(r'\bcotizame\b', 'cotízame', texto)
    texto = re.sub(r'\bcredito\b', 'crédito', texto)
    texto = re.sub(r'\bcuadricula\b', 'cuadrícula', texto)
    texto = re.sub(r'\bdebiste\b', 'debiste', texto)
    texto = re.sub(r'\bdejame\b', 'déjame', texto)
    texto = re.sub(r'\bdeposito\b', 'depósito', texto)
    texto = re.sub(r'\bdescripcion\b', 'descripción', texto)
    texto = re.sub(r'\bdespues\b', 'después', texto)
    texto = re.sub(r'\bdevolucion\b', 'devolución', texto)
    texto = re.sub(r'\bdia\b', 'día', texto)
    texto = re.sub(r'\bdiccionarios\b', 'diccionarios', texto)
    texto = re.sub(r'\bdireccion\b', 'dirección', texto)
    texto = re.sub(r'\bdisculpame\b', 'discúlpame', texto)
    texto = re.sub(r'\beconomica\b', 'económica', texto)
    texto = re.sub(r'\beconomico\b', 'económico', texto)
    texto = re.sub(r'\belectrica\b', 'eléctrica', texto)
    texto = re.sub(r'\belectronico\b', 'electrónico', texto)
    texto = re.sub(r'\bencuadernacion\b', 'encuadernación', texto)
    texto = re.sub(r'\benvio\b', 'envío', texto)
    texto = re.sub(r'\bfacil\b', 'fácil', texto)
    texto = re.sub(r'\bfacturacion\b', 'facturación', texto)
    texto = re.sub(r'\bgrafe\b', 'gafete', texto)
    texto = re.sub(r'\bhabia\b', 'había', texto)
    texto = re.sub(r'\bimaginese\b', 'imagínese', texto)
    texto = re.sub(r'\bimpresion\b', 'impresión', texto)
    texto = re.sub(r'\binalambrico\b', 'inalámbrico', texto)
    texto = re.sub(r'\binformacion\b', 'información', texto)
    texto = re.sub(r'\bjabon\b', 'jabón', texto)
    texto = re.sub(r'\blapices\b', 'lápices', texto)
    texto = re.sub(r'\blapiz\b', 'lápiz', texto)
    texto = re.sub(r'\blinea\b', 'línea', texto)
    texto = re.sub(r'\bmañana\b', 'mañana', texto)
    texto = re.sub(r'\bmercancia\b', 'mercancía', texto)
    texto = re.sub(r'\bnominas\b', 'nóminas', texto)
    texto = re.sub(r'\bnumero\b', 'número', texto)
    texto = re.sub(r'\bofreca\b', 'ofrezca', texto)
    texto = re.sub(r'\bopcion\b', 'opción', texto)
    texto = re.sub(r'\bpaginas\b', 'páginas', texto)
    texto = re.sub(r'\bpapeleria\b', 'papelería', texto)
    texto = re.sub(r'\bporfavor\b', 'por favor', texto)
    texto = re.sub(r'\bproxima\b', 'próxima', texto)
    texto = re.sub(r'\bqueaun\b', 'que aún', texto)
    texto = re.sub(r'\brecepcion\b', 'recepción', texto)
    texto = re.sub(r'\brevision\b', 'revisión', texto)
    texto = re.sub(r'\btambien\b', 'también', texto)
    texto = re.sub(r'\btelefono\b', 'teléfono', texto)
    texto = re.sub(r'\btibiste\b', 'tuviste', texto)
    texto = re.sub(r'\btiviste\b', 'tuviste', texto)
    texto = re.sub(r'\bultimos\b', 'últimos', texto)
    texto = re.sub(r'\bxfavor\b', 'por favor', texto)
    texto = re.sub(r'\bargollo\b', 'argolla', texto)
    texto = re.sub(r'\batengos\b', 'atentos', texto)
    texto = re.sub(r'\bauer\b', 'ayer', texto)
    texto = re.sub(r'\banecesitar\b', 'a necesitar', texto)
    texto = re.sub(r'\bareas\b', 'áreas', texto)
    texto = re.sub(r'\barea\b', 'área', texto)
    texto = re.sub(r'\bart\b', 'artículos', texto)
    texto = re.sub(r'\bart\b', 'artículos', texto)
    texto = re.sub(r'\bbueno+\b', 'bueno', texto)
    texto = re.sub(r'\bcancelare\b', 'cancelaré', texto)
    texto = re.sub(r'\bcancelara\b', 'cancelará', texto)
    texto = re.sub(r'\bcancele\b', 'cancelé', texto)
    texto = re.sub(r'\bcancelo\b', 'canceló', texto)
    texto = re.sub(r'\bcotizacione\b', 'cotizaciones', texto)
    texto = re.sub(r'\bcotizaran\b', 'cotizarán', texto)
    texto = re.sub(r'\bcp\b', 'cada pieza', texto)
    texto = re.sub(r'\bcreditos\b', 'crédito', texto)
    texto = re.sub(r'\bcu\b', 'cada uno', texto)
    texto = re.sub(r'\bcuter\b', 'cutter', texto)
    texto = re.sub(r'\bdescansare\b', 'descansaré', texto)
    texto = re.sub(r'\bdias+\b', 'días', texto)
    texto = re.sub(r'\bdise\b', 'dice', texto)
    texto = re.sub(r'\bdisen\b', 'dicen', texto)
    texto = re.sub(r'\bdises\b', 'dices', texto)
    texto = re.sub(r'\bdulc\b', 'dulce', texto)
    texto = re.sub(r'\beh+\b', 'eh', texto)
    texto = re.sub(r'\beja\b', 'deja', texto)
    texto = re.sub(r'\belimine\b', 'eliminé', texto)
    texto = re.sub(r'\bentregue\b', 'entregué', texto)
    texto = re.sub(r'\beske\b', 'es que', texto)
    texto = re.sub(r'\besra\b', 'era', texto)
    texto = re.sub(r'\bha+\b', 'a', texto)
    texto = re.sub(r'\bestaria\b', 'estaría', texto)
    texto = re.sub(r'\bestra\b', 'esta', texto)
    texto = re.sub(r'\beño\b', 'año', texto)
    texto = re.sub(r'\bpor fa\b', 'porfa', texto)
    texto = re.sub(r'\bfacturre\b', 'facturé', texto)
    texto = re.sub(r'\bfeb\b', 'febrero', texto)
    texto = re.sub(r'\bgenerea\b', 'genera', texto)
    texto = re.sub(r'\bfte\b', 'fuerte', texto)
    texto = re.sub(r'\bgano\b', 'ganó', texto)
    texto = re.sub(r'\bgane\b', 'gané', texto)
    texto = re.sub(r'\bganon\b', 'ganón', texto)
    texto = re.sub(r'\bhjas\b', 'hojas', texto)
    texto = re.sub(r'\bhola+\b', 'hola', texto)
    texto = re.sub(r'\bhpy\b', 'hoy', texto)
    texto = re.sub(r'\bhr\b', 'hora', texto)
    texto = re.sub(r'\bhya\b', 'haya', texto)
    texto = re.sub(r'\bien\b', 'bien', texto)
    texto = re.sub(r'\bjodido+\b', 'jodido', texto)
    texto = re.sub(r'\bla+s\b', 'las', texto)
    texto = re.sub(r'\blapto\b', 'laptop', texto)
    texto = re.sub(r'\blasucursalursal\b', 'la sucursal', texto)
    texto = re.sub(r'\blistav\b', 'lista', texto)
    texto = re.sub(r'\bll han\b', 'llegan', texto)
    texto = re.sub(r'\bllagan\b', 'llegan', texto)
    texto = re.sub(r'\blocjker\b', 'locker', texto)
    texto = re.sub(r'\blopago\b', 'lo pago', texto)
    texto = re.sub(r'\blopez\b', 'lópez', texto)
    texto = re.sub(r'\blt\b', 'litro', texto)
    texto = re.sub(r'\blugarnes\b', 'lugares', texto)
    texto = re.sub(r'\blupitame\b', 'lupita', texto)
    texto = re.sub(r'\bmandaria\b', 'mandaría', texto)
    texto = re.sub(r'\bmands\b', 'mandé', texto)
    texto = re.sub(r'\bmande\b', 'mandé', texto)
    texto = re.sub(r'\bmaquina\b', 'máquina', texto)
    texto = re.sub(r'\bmaskng\b', 'masking', texto)
    texto = re.sub(r'\bmaskin\b', 'masking', texto)
    texto = re.sub(r'\bmaximo\b', 'máximo', texto)
    texto = re.sub(r'\bmaza\b', 'mazatlán', texto)
    texto = re.sub(r'\bmañeno\b', 'mañana', texto)
    texto = re.sub(r'\bmañna\b', 'mañana', texto)
    texto = re.sub(r'\bmetalico\b', 'metálico', texto)
    texto = re.sub(r'\bmetalo\b', 'metálo', texto)
    texto = re.sub(r'\bmetodo\b', 'metódo', texto)
    texto = re.sub(r'\bmil+\b', 'mil', texto)
    texto = re.sub(r'\bml\b', 'mililitro', texto)
    texto = re.sub(r'\bmls\b', 'mililitros', texto)
    texto = re.sub(r'\bmob\b', 'mobiliario', texto)
    texto = re.sub(r'\bmod\b', 'modelo', texto)
    texto = re.sub(r'\bmofico\b', 'modifico', texto)
    texto = re.sub(r'\bmt\b', 'metro', texto)
    texto = re.sub(r'\bmuchisiismas\b', 'muchísimas', texto)
    texto = re.sub(r'\bmuchisismas\b', 'muchísimas', texto)
    texto = re.sub(r'\bmu+y\b', 'muy', texto)
    texto = re.sub(r'\bmñana\b', 'mañana', texto)
    texto = re.sub(r'\bnegr\b', 'negro', texto)
    texto = re.sub(r'\bnombre+\b', 'nombre', texto)
    texto = re.sub(r'\bnomas\b', 'nomás', texto)
    texto = re.sub(r'\bno+\b', 'no', texto)
    texto = re.sub(r'\bnum\b', 'número', texto)
    texto = re.sub(r'\bofi\b', 'oficina', texto)
    texto = re.sub(r'\borden\b', 'órden', texto)
    texto = re.sub(r'\borde\b', 'órden', texto)
    texto = re.sub(r'\bordenes+\b', 'órdenes', texto)
    texto = re.sub(r'\bpagina\b', 'página', texto)
    texto = re.sub(r'\bpaginas\b', 'páginas', texto)
    texto = re.sub(r'\bpagino\b', 'página', texto)
    texto = re.sub(r'\bpaleria\b', 'papelería', texto)
    texto = re.sub(r'\bpapaleria\b', 'papelería', texto)
    texto = re.sub(r'\bpasaen\b', 'pasan', texto)
    texto = re.sub(r'\bpasarne\b', 'pasárme', texto)
    texto = re.sub(r'\bpasarme\b', 'pasárme', texto)
    texto = re.sub(r'\bpasarle\b', 'pasárle', texto)
    texto = re.sub(r'\bpase\b', 'pasé', texto)
    texto = re.sub(r'\bpasop\b', 'pasó', texto)
    texto = re.sub(r'\bpaso\b', 'pasó', texto)
    texto = re.sub(r'\bpañielos\b', 'pañuelos', texto)
    texto = re.sub(r'\bpbasura\b', 'basura', texto)
    texto = re.sub(r'\bpededido\b', 'pedido', texto)
    texto = re.sub(r'\bpedi\b', 'pedí', texto)
    texto = re.sub(r'\bperfect\b', 'perfecto', texto)
    texto = re.sub(r'\bperfecto+\b', 'perfecto', texto)
    texto = re.sub(r'\bperoes\b', 'pero es', texto)
    texto = re.sub(r'\bplis+\b', 'plis', texto)
    texto = re.sub(r'\bplsi\b', 'plis', texto)
    texto = re.sub(r'\bpodran\b', 'podrán', texto)
    texto = re.sub(r'\bpodre\b', 'podré', texto)
    texto = re.sub(r'\bpodria\b', 'podría', texto)
    texto = re.sub(r'\bpodremos\b', 'podremos', texto)
    texto = re.sub(r'\bpofa\b', 'porfa', texto)
    texto = re.sub(r'\bpokitos\b', 'poquitos', texto)
    texto = re.sub(r'\bporfavorcturarle\b', 'porfavor fácturale', texto)
    texto = re.sub(r'\bporfavor+\b', 'porfavor', texto)
    texto = re.sub(r'\bporfavorvir\b', 'porfavor', texto)
    texto = re.sub(r'\bporfavorvot\b', 'porfavor', texto)
    texto = re.sub(r'\bporfi+s\b', 'porfavor', texto)
    texto = re.sub(r'\bporfs\b', 'porfavor', texto)
    texto = re.sub(r'\bpquetes\b', 'paquetes', texto)
    texto = re.sub(r'\bprecio+\b', 'precio', texto)
    texto = re.sub(r'\bpreco\b', 'precio', texto)
    texto = re.sub(r'\bpreecio\b', 'precio', texto)
    texto = re.sub(r'\bpreocupes\b', 'preocupes', texto)
    texto = re.sub(r'\bprocterores\b', 'protectores', texto)
    texto = re.sub(r'\bprod\b', 'producto', texto)
    texto = re.sub(r'\bproduc\b', 'producto', texto)
    texto = re.sub(r'\bprogramacionesperemos\b', 'programacion esperemos', texto)
    texto = re.sub(r'\bpasamosa\b', 'pasamos a', texto) 
    texto = re.sub(r'\bptimiza\b', 'optimiza', texto) 
    texto = re.sub(r'\bpublico\b', 'público', texto) 
    texto = re.sub(r'\bpue\b', 'pues', texto) 
    texto = re.sub(r'\bpues+\b', 'pues', texto) 
    texto = re.sub(r'\bqu\b', 'que', texto) 
    texto = re.sub(r'\bqueaún\b', 'que aún', texto) 
    texto = re.sub(r'\bquecorreo\b', 'que correo', texto) 
    texto = re.sub(r'\bquequiero\b', 'que quiero', texto) 
    texto = re.sub(r'\bquerian\b', 'querían', texto) 
    texto = re.sub(r'\bqueria\b', 'quería', texto) 
    texto = re.sub(r'\bqueriamos\b', 'queríamos', texto) 
    texto = re.sub(r'\bqueusted\b', 'que usted', texto) 
    texto = re.sub(r'\bqueustedes\b', 'que ustedes', texto) 
    texto = re.sub(r'\bralla\b', 'raya', texto) 
    texto = re.sub(r'\bramires\b', 'ramírez', texto) 
    texto = re.sub(r'\bramirez\b', 'ramírez', texto) 
    texto = re.sub(r'\broja+\b', 'roja', texto) 
    texto = re.sub(r'\brojp\b', 'rojo', texto) 
    texto = re.sub(r'\bseguier\b', 'seguir', texto) 
    texto = re.sub(r'\bsucursalursal\b', 'sucursal', texto) 
    texto = re.sub(r'\bsucursalursales\b', 'sucursales', texto) 
    texto = re.sub(r'\bsujetadocumento\b', 'sujeta documento', texto) 
    texto = re.sub(r'\bsujetadocumentos\b', 'sujeta documentos', texto) 
    texto = re.sub(r'\bsya\b', 'ya', texto) 
    texto = re.sub(r'\btons\b', 'entonces', texto) 
    texto = re.sub(r'\btoso\b', 'todo', texto) 
    texto = re.sub(r'\btoy\b', 'estoy', texto) 
    texto = re.sub(r'\bla trabajacion\b', 'el trabajo', texto) 
    texto = re.sub(r'\bunica\b', 'única', texto) 
    texto = re.sub(r'\bultimo\b', 'último', texto) 
    texto = re.sub(r'\bultima\b', 'última', texto) 
    texto = re.sub(r'\buen\b', 'buen', texto) 
    texto = re.sub(r'\bunico\b', 'único', texto) 
    texto = re.sub(r'\bunica\b', 'única', texto) 
    texto = re.sub(r'\buro rudo\b', 'uso rudo', texto) 
    texto = re.sub(r'\butil\b', 'útil', texto) 
    texto = re.sub(r'\butiles\b', 'útiles', texto) 
    texto = re.sub(r'\butilices\b', 'útilices', texto) 
    texto = re.sub(r'\busare\b', 'usaré', texto) 
    texto = re.sub(r'\bvea\b', 'verdad', texto) 
    texto = re.sub(r'\bvince\b', 'vine', texto) 
    texto = re.sub(r'\bvrd+\b', 'verdad', texto) 
    texto = re.sub(r'\bvuand\b', 'cuando', texto) 
    texto = re.sub(r'\byase\b', 'ya sé', texto) 
    texto = re.sub(r'\bbhes\b', 'vez', texto) 
    texto = re.sub(r'\bbie\b', 'bien', texto) 
    texto = re.sub(r'\bbolsasa\b', 'bolsas', texto) 
    texto = re.sub(r'\bbuen+\b', 'buen', texto) 
    texto = re.sub(r'\bbue\b', 'buen', texto) 
    texto = re.sub(r'\bbuenl\b', 'bueno', texto) 
    texto = re.sub(r'\bben\b', 'ven', texto) 

    texto = texto.replace("avsio", "aviso")
    texto = texto.replace("ocmo", "como")


    if(("a ti" not in texto) or ("a tí" not in texto)):
        texto = re.sub(r'\bti,\b', 'a tí,', texto)
    texto = re.sub(r'\bseman\b', 'semana', texto)

    #texto = re.sub(r'[áéíóúñ]', lambda m: {'á':'a','é':'e','í':'i','ó':'o','ú':'u', 'ñ':'n'}[m.group()], texto)

    return texto

def normalizacion_nombres(texto):
    texto = texto.replace("aleajandra", "alejandra")
    texto = texto.replace("aleajandra", "alejanda")
    texto = re.sub(r'\baaracely\b', "aracely", texto)
    texto = texto.replace("kharely", "karely")
    texto = texto.replace("kharély", "karely")
    texto = texto.replace("karelu", "karely")
    texto = texto.replace("rossy", "rosy")
    texto = texto.replace("briceidaa", "briceida")
    texto = texto.replace("betzavel", "betzabel")
    texto = texto.replace("zuleika", "zuleica")
    texto = texto.replace("zuelika", "zuleica")
    texto = texto.replace("casandra", "cassandra")
    texto = texto.replace("armandoo", "armando")
    texto = texto.replace("racely", "aracely")

    texto = texto.replace("hernandez", "hernández")
    texto = texto.replace("ka tia", "katia")
    texto = texto.replace("cerlox", "xerox")
    texto = texto.replace("victorio", "victoria")
    texto = texto.replace("scoch", "scotch")
    texto = texto.replace("postis", "post it")
    texto = texto.replace("post ic", "post it")
    texto = texto.replace("suc", "sucursal")
    texto = texto.replace("kraf", "craft")
    texto = texto.replace("postick", "post it")

    texto = re.sub(r'\bdanielaaaaaaaaaa\b', 'daniela', texto)
    texto = re.sub(r'\bculiacan\b', 'culiacán', texto)
    texto = re.sub(r'\bmazatlan\b', 'mazatlán', texto)
    texto = re.sub(r'\bpos it\b', 'post it', texto)
    texto = re.sub(r'\bscorch\b', 'scotch', texto)
    texto = re.sub(r'\bklenex\b', 'kleenex', texto)
    texto = re.sub(r'\bscoth\b', 'scotch', texto)
    texto = re.sub(r'\bsctoch\b', 'scotch', texto)
    texto = re.sub(r'\bstcott\b', 'scotch', texto)
    texto = texto.replace('vistoria', 'victoria')
    texto = re.sub(r'\bwatsap\b', 'whatsapp', texto)
    return texto

def normalizacion_puntuacion(texto):
    texto = texto.replace("???", "?")
    texto = texto.replace("??", "?")
    texto = texto.replace("¿?", "?")
    texto = texto.replace("?¡", "?")
    texto = texto.replace(" ,", ",")
    texto = texto.replace("  ", " ")
    texto = texto.replace("   ", " ")
    texto = texto.replace(",.", "") 
    texto = texto.replace("ð", "")
    texto = texto.replace("Ÿ", "")
    texto = texto.replace("˜", "")
    texto = texto.replace("â", "")
    texto = texto.replace("œ", "")
    texto = texto.replace("¨", "")
    texto = texto.replace("Š", "")
    texto = texto.replace(";", "")
    texto = texto.replace("´", "")
    texto = re.sub(r'\bç\b', '', texto)


    if(".com" not in texto):
        texto = texto.replace(".", " ")
        #texto = texto.replace(" ?", "?")
        texto = texto.replace("{", "")
        texto = texto.replace("}", "")
        texto = texto.replace("[", "")
        texto = texto.replace("]", "")
        texto = texto.replace("☹️", "")
        texto = texto.replace("☺️", "")
        texto = texto.replace("*", "")
        texto = texto.replace("-¡", "")
        texto = texto.replace("@", "")
        texto = texto.replace("<", "")
        texto = texto.replace(">", "")
        texto = texto.replace(":", "")
        texto = texto.replace("/", "")
        texto = texto.replace("°", "")
        texto = texto.replace("--", "")
        texto = texto.replace(",.", "") 
        texto = texto.replace("()", "")
        texto = texto.replace("}?", "")
    return texto

def normalizacion_bigramas(texto):
    norm_bigramas = {"d efavor": "de favor",
                     "con tigo": "contigo",
                     "alomejor": "a lo mejor",
                     "claroquesi": "claro que si",
                     " ala ": "a la",
                     "buend ia": "buen día",
                     " are ": "hare",
                     "acolgar": "a colgar",
                     " ami ": "a mi",
                     " aprogramacion ": "a programacion",
                     " aque ": "a que",
                     " avisasi ": "avisas si",
                     " yavi ": "ya vi",
                     " esque ": "es que",
                     "estabien": "esta bien",
                     "paquetede": "paquete de",
                     "comfu": "con su",
                     "ra tito": "ratito",
                     "tintaquecolor": "tinta que color",
                     "automa tico": "automatico",
                     "corpora tivo": "corporativo",
                     "pa ti": "para ti",
                     "a tu": "a ti",
                     "a ty": "a ti",
                     "re sirve": "te sirve",
                     "como estas": "cómo estás",
                     "como esta": "cómo está",
                     "buenosd ias": "buenos dias",
                     "sies": "si es",
                     "esque": "es que",
                     "cartaoficio": " carta oficio",
                     "te pasara": "te pasará",
                     "podemos pasara": "podemos pasar",
                     "pgafete": "para gafete",
                     "smi": "a mi",
                     "a mi": "a mi",
                     "archivo muerto": "archivo",
                     "liquid papes": "liquid paper",
                     "nadamas": "nada más",
                     "marcatextos": "marca textos",
                     "aynooooooo": "ay nooooooo",
                     "esa cuanta": "esa cuenta",
                     "citas escorsh": "cintas scotch",
                     "si si me sirve": "si, si me sirve",
                     "notas adh": "notas adhesivas",
                     "agarrapapeles": "sujetapapeles",
                     "amodificar": "a modificar",
                     "austed": "a usted",
                     "encuanto": "en cuánto",
                     }

    for bg_erroneo, bg_forma in norm_bigramas.items():
        # reemplaza el bigrama erroneo con su forma correcta
        texto = texto.replace(bg_erroneo, bg_forma)
    
    return texto

def preprocess_chat(filename, trie_flag = 0):
    
    #pre-procesamiento del texto
    with open(filename, "r", encoding = "utf-8") as f:
        raw_chat = []
        processed_chat = []
        for line in f.readlines():
            line = line.replace("\n", "")
            raw_chat.append(line)

        for line in raw_chat:
            # Formato nuevo: [DD/MM/YY, HH:MM:SS p.m.] Author: message
            if line.startswith("["):
                bracket_end = line.find("]")
                if bracket_end == -1:
                    continue
                content_raw = line[bracket_end + 1:].strip()
            elif line and line[0].isdigit():
                # Formato viejo WhatsApp: DD/MM/YYYY, HH:MM - Author: message
                parts = line.split(" - ", 1)
                if len(parts) < 2:
                    continue
                content_raw = parts[1].strip()
            else:
                # Formato FB/directo: Author: message (sin fecha ni timestamp)
                content_raw = line

            content = content_raw.split(":", 1)

            if(len(content) > 1):
                author = content[0].strip()
                text = content[1].lower().strip()
                # quitar emojis del texto
                if(validar_alpha_en_texto(text) and validar_emoji_en_texto(text)):
                    text = limpiar_emojis_texto(text)

                # normalizar errores de texto, puntuacion y bigramas
                text = normalizacion_texto(text)
                text = normalizacion_puntuacion(text)
                text = normalizacion_bigramas(text)
                text = normalizacion_nombres(text)

                processed_text = author + ":" + text
                words_list = re.split(r"[ .,]+", text)
                
                if(trie_flag):
                    found_words, similar_words, unfound_words = trie.process_text_optimized(words_list)
                    unfound_words.append(unfound_words)

                if(("<Multimedia omitido>" not in line) and\
                   ("Eliminaste este mensaje" not in line) and \
                   ("se eliminó este mensaje" not in line) and \
                   (("se elim" not in line) and ("este mensaje" not in line)) and\
                   ("(archivo adjunto)"not in line) and \
                   (False == validar_emoji_en_texto(line))):
                    processed_chat.append(processed_text)

    new_file = filename.replace(".txt", "_processed.txt")

    with open(new_file, "w+", encoding="utf-8") as f2:
        for line in processed_chat:
            f2.write(line + "\n")
    
    if(trie_flag):
        with open("unfound_words.txt", "a+", encoding = "utf-8") as f3:
            for element in unfound_words:
                f3.write(str(element) + "\n")

def extract_author_text(line: str) -> tuple[str, str]:
    """
    Parsea una linea en formato 'author:text' de mensajes_processed.txt.
    Retorna (author, text). Si no hay ':', retorna ('', line).
    """
    parts = line.strip().split(":", 1)
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip()
    return "", line.strip()


def clean_for_sentiment(texto: str) -> str:
    """
    Limpieza adicional orientada a sentiment analysis:
    - Elimina URLs
    - Elimina menciones @usuario
    - Colapsa espacios multiples
    - Elimina tokens numericos puros (precios, telefonos no aportan sentimiento)
    - Elimina tokens de un solo caracter
    """
    texto = re.sub(r"https?://\S+|www\.\S+", "", texto)
    texto = re.sub(r"@\w+", "", texto)
    texto = re.sub(r"\b\d+\b", "", texto)
    tokens = [t for t in texto.split() if len(t) > 1]
    return " ".join(tokens).strip()


def normalize_for_sentiment(texto: str) -> str:
    """
    Pipeline completo para preparar un mensaje antes de sentiment analysis.
    Aplica: correccion de typos -> puntuacion -> bigramas -> limpieza de sentimiento.
    """
    texto = normalizacion_texto(texto)
    texto = normalizacion_puntuacion(texto)
    texto = normalizacion_bigramas(texto)
    texto = clean_for_sentiment(texto)
    return texto


def run():
    corpus_dir = os.path.join(os.path.dirname(__file__), "corpus")
    for txt_file in glob.glob(os.path.join(corpus_dir, "**", "*.txt"), recursive=True):
        if not txt_file.endswith("_processed.txt"):
            print(f"Procesando: {txt_file}")
            preprocess_chat(txt_file)


if __name__ == "__main__":
    run()